// File: backend/src/modules/report/report.model.js

const mongoose = require('mongoose');

const reportSchema = new mongoose.Schema({
  // Report Identification
  reportId: {
    type: String,
    unique: true,
    required: true
  },
  
  // Report Type
  type: {
    type: String,
    enum: [
      'waiter_performance',
      'cook_performance', 
      'cashier_performance',
      'sales_summary',
      'order_analytics',
      'staff_comparison',
      'daily_summary',
      'weekly_summary',
      'monthly_summary',
      'custom'
    ],
    required: true
  },
  
  // Report Scope
  scope: {
    type: String,
    enum: ['individual', 'team', 'department', 'system'],
    default: 'system'
  },
  
  // Subject (who the report is about)
  subjectUser: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  
  // Generated by
  generatedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  // Time Period
  period: {
    startDate: {
      type: Date,
      required: true
    },
    endDate: {
      type: Date,
      required: true
    }
  },
  
  // Report Data (flexible JSON storage)
  data: {
    type: mongoose.Schema.Types.Mixed,
    required: true
  },
  
  // Metrics Summary
  summary: {
    totalOrders: Number,
    totalRevenue: Number,
    avgOrderValue: Number,
    completionRate: Number,
    avgWaitTime: Number,
    // Add more as needed
  },
  
  // Status
  status: {
    type: String,
    enum: ['pending', 'generated', 'downloaded', 'shared'],
    default: 'generated'
  },
  
  // Export Info
  exportedAt: Date,
  exportFormat: {
    type: String,
    enum: ['pdf', 'csv', 'excel', 'json']
  },
  
  // Sharing
  sharedWith: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }],
  
  // Notes/Comments
  notes: String,
  
}, {
  timestamps: true
});

// Indexes
reportSchema.index({ generatedBy: 1, createdAt: -1 });
reportSchema.index({ subjectUser: 1, type: 1 });
reportSchema.index({ 'period.startDate': 1, 'period.endDate': 1 });

// Auto-generate reportId
reportSchema.pre('save', async function(next) {
  if (!this.reportId) {
    const count = await this.constructor.countDocuments();
    this.reportId = `RPT-${Date.now()}-${String(count + 1).padStart(5, '0')}`;
  }
  next();
});

module.exports = mongoose.model('Report', reportSchema);